all:
  configuration:
    drev:
      validation_odg: 'admin'
      logement_adresse: false
      denomination_auto: true
      denomination_biodynamie: true
      engagement_pdf: true
      pdf_unique_region: true
      send_to_innovagro: true
      denominations_extra:
        BIODYNAMIE: "Biodynamie hors conversion"
