<?php

class DRCsvFile extends DouaneCsvFile
{
  const CSV_TYPE_DR = 'DR';
  const CSV_LIGNE_CODE_RECOLTE_L4 = "4";
  const CSV_LIGNE_CODE_RECOLTE_L4_ORIGINALE = "4B";
  const CSV_LIGNE_CODE_RECOLTE_L5 = "5";
  const CSV_LIGNE_CODE_USAGESIND_L16 = "16";
  const CSV_LIGNE_CODE_SUPERFICIE_L4 = "4";
  const CSV_LIGNE_CODE_ACHETEUR_RAISINS_L6 = "6";
  const CSV_LIGNE_CODE_ACHETEUR_MOUTS_L7 = "7";
  const CSV_LIGNE_CODE_COOPERATIVE_L8 = "8";
  const CSV_LIGNE_CODE_VOLUME_L9 = "9";
  const CSV_LIGNE_CODE_AUTRES_VOLUMES_NON_VINIFIES_L12 = "12";
  const CSV_LIGNE_CODE_VOLUME_SANS_IG_L14 = "14";
  const CSV_LIGNE_CODE_RECOLTE_NETTE_L15 = "15";
  const CSV_LIGNE_CODE_VSI_L18 = "18";
  const CSV_LIGNE_CODE_VCI_L19 = "19";
  const CSV_LIGNE_CODE_ACHAT_TOLERANCE = "99";

}
