<?php

class DRCsvFile extends DouaneCsvFile
{
  const CSV_TYPE_DR = 'DR';
  const CSV_LIGNE_CODE_RECOLTE_L5 = "5";
  const CSV_LIGNE_CODE_USAGESIND_L16 = "16";
  const CSV_LIGNE_CODE_SUPERFICIE_L4 = "4";
  const CSV_LIGNE_CODE_AHCTEUR_RAISINS_L6 = "6";
  const CSV_LIGNE_CODE_AHCTEUR_MOUTS_L7 = "7";
  const CSV_LIGNE_CODE_COOPERATIVE_L8 = "8";
  const CSV_LIGNE_CODE_VOLUME_L9 = "9";
  const CSV_LIGNE_CODE_RECOLTE_NETTE_L15 = "15";
  const CSV_LIGNE_CODE_VCI_L19 = "19";
  const CSV_LIGNE_CODE_ACHAT_TOLERANCE = "99";

}
