<?php

class SV11CsvFile extends DouaneCsvFile
{
  const CSV_TYPE_SV11 = 'SV11';
  const CSV_LIGNE_CODE_SUPERFICIE = "4";
  const CSV_LIGNE_CODE_LIVRAISON_COOP = "8";
  const CSV_LIGNE_CODE_VOLUME_APTE = "15";
  const CSV_LIGNE_CODE_VOLUME_ELIMINIE = "16";
  const CSV_LIGNE_CODE_VOLUME_EAU = "17";
  const CSV_LIGNE_CODE_VOLUME_VSI = "18";
  const CSV_LIGNE_CODE_VOLUME_VCI = "19";
}
