<?php

class SV12CsvFile extends DouaneCsvFile
{
  const CSV_TYPE_SV12 = 'SV12';
  const CSV_LIGNE_CODE_SUPERFICIE = "4";
  const CSV_LIGNE_CODE_RECOLTE_RAISINS = "06kg";
  const CSV_LIGNE_CODE_RECOLTE_MOUTS = "07";
  const CSV_LIGNE_CODE_VOLUME_RAISINS = "15VF";
  const CSV_LIGNE_CODE_VOLUME_MOUTS = "15M";
  const CSV_LIGNE_CODE_VOLUME_TOTAL = "15";
}
