all:
  configuration:
    communes:
      insee2commune:
        06158: "VILLARS-SUR-VAR"
        13002: "ALLAUCH"
        13015: "BOUC-BEL-AIR"
        13023: "CEYRESTE"
        13025: "CHATEAUNEUF-LE-ROUGE"
        13028: "CIOTAT"
        13030: "CUGES-LES-PINS"
        13060: "MEYREUIL"
        13062: "MIMET"
        13072: "PEYNIER"
        13079: "PUYLOUBIER"
        13085: "ROQUEFORT-LA-BEDOULE"
        13087: "ROUSSET"
        13107: "SIMIANE-COLLONGUE"
        13109: "THOLONET"
        13110: "TRETS"
        83004: "ARCS"
        83008: "BAGNOLS-EN-FORET"
        83016: "BEAUSSET"
        83018: "BESSE-SUR-ISSOLE"
        83019: "BORMES-LES-MIMOSAS"
        83026: "CABASSE"
        83027: "CADIERE-D'AZUR"
        83028: "CALLAS"
        83031: "CANNET-DES-MAURES"
        83032: "CARCES"
        83033: "CARNOULES"
        83034: "CARQUEIRANNE"
        83035: "CASTELLET"
        83036: "CAVALAIRE-SUR-MER"
        83042: "COGOLIN"
        83043: "COLLOBRIERES"
        83045: "CORRENS"
        83046: "COTIGNAC"
        83047: "CRAU"
        83048: "CROIX-VALMER"
        83049: "CUERS"
        83050: "DRAGUIGNAN"
        83051: "ENTRECASTEAUX"
        83053: "EVENOS"
        83054: "FARLEDE"
        83056: "FIGANIERES"
        83057: "FLASSANS-SUR-ISSOLE"
        83058: "FLAYOSC"
        83061: "FREJUS"
        83062: "GARDE"
        83063: "GARDE-FREINET"
        83065: "GASSIN"
        83067: "GONFARON"
        83068: "GRIMAUD"
        83069: "HYERES"
        83071: "LONDE-LES-MAURES"
        83072: "LORGUES"
        83073: "LUC"
        83075: "MAYONS"
        83079: "MOLE"
        83083: "MONTFORT-SUR-ARGENS"
        83085: "MOTTE"
        83086: "MUY"
        83091: "PIERREFEU-DU-VAR"
        83092: "PIGNANS"
        83094: "PLAN-DE-LA-TOUR"
        83096: "POURCIEUX"
        83097: "POURRIERES"
        83098: "PRADET"
        83099: "PUGET-SUR-ARGENS"
        83100: "PUGET-VILLE"
        83101: "RAMATUELLE"
        83107: "ROQUEBRUNE-SUR-ARGENS"
        83112: "SAINT-CYR-SUR-MER"
        83115: "SAINTE-MAXIME"
        83117: "SAINT-PAUL-EN-FORET"
        83118: "SAINT-RAPHAEL"
        83119: "SAINT-TROPEZ"
        83123: "SANARY-SUR-MER"
        83124: "SEILLANS"
        83129: "SIX-FOURS-LES-PLAGES"
        83130: "SOLLIES-PONT"
        83134: "TARADEAU"
        83136: "THORONET"
        83141: "TRANS-EN-PROVENCE"
        83144: "VALETTE-DU-VAR"
        83148: "VIDAUBAN"
        83154: "SAINT-ANTONIN-DU-VAR"
      insee2secteur:
        06158: "ALPES MARITIMES	"
        83032: "ARGENS BESSILLON"
        83045: "ARGENS BESSILLON"
        83046: "ARGENS BESSILLON"
        83051: "ARGENS BESSILLON"
        83072: "ARGENS BESSILLON"
        83083: "ARGENS BESSILLON"
        83154: "ARGENS BESSILLON"
        83136: "ARGENS BESSILLON"
        83016: "BASSIN DU BEAUSSET"
        83027: "BASSIN DU BEAUSSET"
        83035: "BASSIN DU BEAUSSET"
        13023: "BASSIN DU BEAUSSET"
        13028: "BASSIN DU BEAUSSET"
        13030: "BASSIN DU BEAUSSET"
        83053: "BASSIN DU BEAUSSET"
        13085: "BASSIN DU BEAUSSET"
        83112: "BASSIN DU BEAUSSET"
        83123: "BASSIN DU BEAUSSET"
        83129: "BASSIN DU BEAUSSET"
        83028: "DRACENIE"
        83050: "DRACENIE"
        83056: "DRACENIE"
        83058: "DRACENIE"
        83117: "DRACENIE"
        83124: "DRACENIE"
        83134: "DRACENIE"
        83141: "DRACENIE"
        83008: "FREJUS"
        83061: "FREJUS"
        83085: "FREJUS"
        83086: "FREJUS"
        83099: "FREJUS"
        83107: "FREJUS"
        83118: "FREJUS"
        83036: "GOLF DE SAINT TROPEZ"
        83042: "GOLF DE SAINT TROPEZ"
        83048: "GOLF DE SAINT TROPEZ"
        83065: "GOLF DE SAINT TROPEZ"
        83068: "GOLF DE SAINT TROPEZ"
        83101: "GOLF DE SAINT TROPEZ"
        83119: "GOLF DE SAINT TROPEZ"
        83019: "LA LONDE"
        83069: "LA LONDE"
        83071: "LA LONDE"
        83063: "MAURES INTERIEURS"
        83079: "MAURES INTERIEURS"
        83094: "MAURES INTERIEURS"
        83115: "MAURES INTERIEURS"
        83004: "NOTRE DAME DES ANGES"
        83031: "NOTRE DAME DES ANGES"
        83067: "NOTRE DAME DES ANGES"
        83073: "NOTRE DAME DES ANGES"
        83075: "NOTRE DAME DES ANGES"
        83092: "NOTRE DAME DES ANGES"
        83148: "NOTRE DAME DES ANGES"
        83033: "PIERREFEU"
        83034: "PIERREFEU"
        83043: "PIERREFEU"
        83047: "PIERREFEU"
        83049: "PIERREFEU"
        83054: "PIERREFEU"
        83062: "PIERREFEU"
        83091: "PIERREFEU"
        83098: "PIERREFEU"
        83100: "PIERREFEU"
        83130: "PIERREFEU"
        83144: "PIERREFEU"
        83018: "PLATEAU KARSTIQUE"
        83026: "PLATEAU KARSTIQUE"
        83057: "PLATEAU KARSTIQUE"
        13002: "SAINTE VICTOIRE"
        13015: "SAINTE VICTOIRE"
        13025: "SAINTE VICTOIRE"
        13060: "SAINTE VICTOIRE"
        13062: "SAINTE VICTOIRE"
        13072: "SAINTE VICTOIRE"
        83096: "SAINTE VICTOIRE"
        83097: "SAINTE VICTOIRE"
        13079: "SAINTE VICTOIRE"
        13087: "SAINTE VICTOIRE"
        13107: "SAINTE VICTOIRE"
        13109: "SAINTE VICTOIRE"
        13110: "SAINTE VICTOIRE"
