all:
  configuration:
    communes:
      insee2commune:
        "41204": "Saint-Claude-de-Diray"
        "41034": "CHAMBORD"
        "41145": "MONTHOU-SUR-BIEVRE"
        "41061": "Cormeray"
        "41059": "Le Controis-en-Sologne"
        "41147": "LES MONTILS"
        "41104": "HUISSEAU-SUR-COSSON"
        "41148": "MONTLIVAULT"
        "41052": "CHITENAY"
        "41129": "MASLIVES"
        "41150": "MONT-PRES-CHAMBORD"
        "41067": "Cour-Cheverny"
        "41262": "TOUR-EN-SOLOGNE"
        "41031": "CELLETTES"
        "41207": "SAINT-DYE-SUR-LOIRE"
        "41233": "Sambin"
        "41050": "Cheverny"
        "41220": "SAINT-LAURENT-NOUAN"
        "41094": "FRESNES"
        "41295": "Vineuil"
        "41029": "Candé-sur-Beuvron"
        "41155": "MUIDES-SUR-LOIRE"
        "41246": "SEUR"
        "41204": "Saint-Claude-de-Diray"
        "41034": "CHAMBORD"
        "41145": "MONTHOU-SUR-BIEVRE"
        "41061": "Cormeray"
        "41059": "Le Controis-en-Sologne"
        "41147": "LES MONTILS"
        "41104": "HUISSEAU-SUR-COSSON"
        "41148": "MONTLIVAULT"
        "41052": "CHITENAY"
        "41129": "MASLIVES"
        "41150": "MONT-PRES-CHAMBORD"
        "41067": "Cour-Cheverny"
        "41262": "TOUR-EN-SOLOGNE"
        "41031": "CELLETTES"
        "41207": "SAINT-DYE-SUR-LOIRE"
        "41233": "Sambin"
        "41050": "Cheverny"
        "41220": "SAINT-LAURENT-NOUAN"
        "41094": "FRESNES"
        "41295": "Vineuil"
        "41029": "Candé-sur-Beuvron"
        "41155": "MUIDES-SUR-LOIRE"
        "41246": "SEUR"
