all:
  configuration:
    drev:
      mentions_complementaire: true
      import_with_mentions_complementaire: true
      validation_odg: 'auto'
      etape_superficie: false
      dr_douane_required: false
      degustation: true
      specificite_lot: true
      engagement_pdf: true
      specificites: #la liste s'additionne avec la config globale du plugin drev
        TerraVitis: "Terra Vitis"
