# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/11-App

# default values
all:
  organisme:
    nom: "Centre Loire"
  elasticversion: '2.4.6'
  float:
    default_decimal_format: 2
    max_decimal_authorized: 4
  societe:
    format_identifiant: "%06d"
  donnees_viticoles:
    lot_saisie_mention_cepage_active: false
    secteurs:
      CHATEAUMEILLANT: "CHATEAUMEILLANT"
      GIENNOIS_NORD: "GIENNOIS_NORD"
      GIENNOIS_SUD: "GIENNOIS_SUD"
      MENETOU: "MENETOU"
      MENETOU_NORD_AOC: "MENETOU_NORD_AOC"
      MENETOU_ZONE_CENTRE: "MENETOU_ZONE_CENTRE"
      POUILLY: "POUILLY"
      POUILLY_LE_BOUCHOT: "POUILLY_LE_BOUCHOT"
      POUILLY_LES_BERTHIERS: "POUILLY_LES_BERTHIERS"
      POUILLY_LES_LOGES: "POUILLY_LES_LOGES"
      POUILLY_SAINT_ANDELAIN: "POUILLY_SAINT_ANDELAIN"
      POUILLY_SOUMARD: "POUILLY_SOUMARD"
      POUILLY_TRACY: "POUILLY_TRACY"
      QUINCY_BOURG: "QUINCY_BOURG"
      QUINCY_EXTERIEUR: "QUINCY_EXTERIEUR"
      QUINCY_MAISON_BLANCHE: "QUINCY_MAISON_BLANCHE"
      QUINCY_BRINAY: "QUINCY_BRINAY"
      QUINCY_PREUILLY: "QUINCY_PREUILLY"
      QUINCY_CERBOIS: "QUINCY_CERBOIS"
      QUINCY_BUISSON_LONG: "QUINCY_BUISSON_LONG"
      QUINCY_REUILLY: "QUINCY_REUILLY"
      REUILLY_BOIS_ST_DENIS: "REUILLY_BOIS_ST_DENIS"
      REUILLY_BOURG: "REUILLY_BOURG"
      REUILLY_CHAIS: "REUILLY_CHAIS"
      REUILLY_EST: "REUILLY_EST"
      REUILLY_LAZENAY: "REUILLY_LAZENAY"
      REUILLY_OUEST: "REUILLY_OUEST"
      REUILLY_SUD: "REUILLY_SUD"
      SANCERRE: "SANCERRE"
      SANCERRE_AMIGNY: "SANCERRE_AMIGNY"
      SANCERRE_BUE: "SANCERRE_BUE"
      SANCERRE_CHAVIGNOL: "SANCERRE_CHAVIGNOL"
      SANCERRE_CREZANCY: "SANCERRE_CREZANCY"
      SANCERRE_ISOLES: "SANCERRE_ISOLES"
      SANCERRE_MAIMBRAY: "SANCERRE_MAIMBRAY"
      SANCERRE_MENETOU_RATEL: "SANCERRE_MENETOU_RATEL"
      SANCERRE_MENETREOL: "SANCERRE_MENETREOL"
      SANCERRE_MONTIGNY: "SANCERRE_MONTIGNY"
      SANCERRE_STE_GEMME: "SANCERRE_STE_GEMME"
      SANCERRE_ST_SATUR: "SANCERRE_ST_SATUR"
      SANCERRE_SURY_EN_VAUX: "SANCERRE_SURY_EN_VAUX"
      SANCERRE_THAUVENAY_VINON: "SANCERRE_THAUVENAY_VINON"
      SANCERRE_VEAUGUES: "SANCERRE_VEAUGUES"
      SANCERRE_VERDIGNY: "SANCERRE_VERDIGNY"
  communes:
    denominations:
