all:
  configuration:
    drev:
      mentions_complementaire: true
      import_with_mentions_complementaire: true
      validation_odg: 'auto'
      habilitation_inao: true
      cgu: true
      send_email_operateur: false
