all:
  configuration:
    parcellaire:
      ecart_rangs_max: 250
      ecart_pieds_min:  80
      aires:
        muscadet:
          name: "Muscadet"
          color: "#fdfad7"
          denomination_id: "00211"
        muscadet-coteaux-loire:
          name: "Muscadet Coteaux de la Loire"
          color: "#cae370"
          denomination_id: "00212"
        muscadet-cotes-grandlieu:
          name: "Muscadet Côtes de Grandlieu"
          color: "#bba981"
          denomination_id: "00213"
        muscadet-sevre-maine:
          name: "Muscadet Sèvre et Maine"
          color: "#ecbe5b"
          denomination_id: "00214"
        coteaux-ancenis:
          name: "Coteaux d'Ancenis"
          color: "#520100"
          denomination_id: "02020"
        Gros Plant:
          name: "Gros Plant"
          color: "#008d13"
          denomination_id: "02023"
