all:
  configuration:
    habilitation:
      produits:
        convert:
          appellation_PINOTNOIR: appellation_ALSACE
          appellation_PINOTNOIRROUGE: appellation_ALSACE
          appellation_COMMUNALE: appellation_ALSACE
          appellation_LIEUDIT: appellation_ALSACE
          appellation_ALSACEBLANC: appellation_ALSACE
      activites:
        PRODUCTEUR: "Producteur de raisins"
        PRODUCTEUR_MOUTS: "Producteur de moût"
        CONDITIONNEUR: "Conditionneur"
        VINIFICATEUR: "Vinificateur"
        ELABORATEUR: "Élaborateur"
        VRAC: "Détenteur de vin en vrac"
        MARC: "Producteur de Marc"
        DISTILLATEUR: "Distillateur"
        METTEUR_EN_MARCHE: "Metteur en Marché"
        DISTILLATEUR: 'Distillateur'
        ELEVEUR: 'Eleveur'
        PRESTATAIRE_DE_SERVICE: 'Prestataire de service'
      demande:
        listing: false
        statuts:
          DEPOT: "Dépôt"
          RELANCE_1: "Relance n°1"
          RELANCE_2: "Relance n°2"
          RELANCE_3: "Relance n°3"
          COMPLET: "Complet"
          TRANSMIS_QUALISUD: "Transmis à QUALISUD"
          VALIDE_QUALISUD: "Validé par QUALISUD"
          REFUSE_QUALISUD: "Refusé par QUALISUD"
          TRANSMIS_INAO: "Transmis à l'INAO"
          VALIDE_INAO: "Validé par l'INAO"
          REFUSE_INAO: "Refusé par l'INAO"
          VALIDE: "Validé"
          REFUSE: "Refusé"
          ANNULE: "Annulé"
        automatique:
          VALIDE_QUALISUD: VALIDE
          REFUSE_QUALISUD: REFUSE
          VALIDE_INAO: VALIDE
          REFUSE_INAO: REFUSE
        habilitations:
          HABILITATION:
            COMPLET: DEMANDE_HABILITATION
            VALIDE_QUALISUD: HABILITE
            VALIDE_INAO: HABILITE
            VALIDE: HABILITE
            REFUSE: REFUS
            ANNULE: ANNULÉ
          RETRAIT:
            COMPLET: DEMANDE_RETRAIT
            VALIDE: RETRAIT
            REFUSE: HABILITE
            ANNULE: HABILITE
          RESILIATION:
            COMPLET: DEMANDE_RESILIATION
            VALIDE: RESILIE
            REFUSE: HABILITE
            ANNULE: HABILITE
