all:
  configuration:
    communes:
      insee2commune:
        "03053": "CHANTELLE",
        "03115": "FLEURIEL",
        "03140": "CHAREIL CINTRAT",
        "03150": "MONTAIGU LE BLIN",
        "03188": "MONTORD",
        "03210": "BESSON",
        "03210": "BRESNAY",
        "03210": "CHEMILLY",
        "03430": "COSNE D'ALLIER",
        "03450": "VICQ",
        "03500": "BRANSAT",
        "03500": "CESSET",
        "03500": "CHATEL DE NEUVRE",
        "03500": "MONETAY SUR ALLIER",
        "03500": "SAINT POURCAIN SUR SIOULE",
        "03500": "SAULCET",
        "14170": "SAINT PIERRE SUR DIVES",
        "16370": "BREVILLE",
        "18120": "BRINAY",
        "18120": "CERBOIS",
        "18120": "QUINCY",
        "18130": "DUN SUR AURON",
        "18190": "VENESMES",
        "18220": "PARASSY",
        "18240": "BOULLERET",
        "18240": "SAINTE GEMME EN SANCERROIS",
        "18240": "SAINTE GEMMES EN SANCERROIS",
        "18250": "HUMBLIGNY",
        "18250": "MONTIGNY",
        "18270": "SAINT MAUR",
        "18270": "SIDIALLES",
        "18300": "BANNAY",
        "18300": "BUE",
        "18300": "CREZANCY EN SANCERRE",
        "18300": "MENETOU RATEL",
        "18300": "MENETOU-RATEL",
        "18300": "SAINT SATUR"
        "18300": "SAINT SATUR",
        "18300": "SANCERRE",
        "18300": "SURY EN VAUX",
        "18300": "THAUVENAY",
        "18300": "VERDIGNY",
        "18300": "VINON",
        "18301": "CREZANCY EN SANCERRE",
        "18310": "GRASAY",
        "18370": "CHATEAUMEILLANT"
        "18370": "CHATEAUMEILLANT",
        "21220": "MOREY SAINT DENIS",
        "21703": "NUITS SAINT GEORGES",
        "22150": "PLOEUC SUR LIE",
        "23220": "MORTROUX",
        "23270": "BETETE",
        "24500": "EYMET",
        "26150": "DIE",
        "30300": "BEAUCAIRE",
        "33070": "BORDEAUX CEDEX",
        "33100": "BORDEAUX",
        "33290": "BLANQUEFORT",
        "33292": "BLANQUEFORT cedex",
        "33720": "LANDIRAS",
        "34070": "MONTPELLIER",
        "34500": "BEZIERS",
        "35600": "REDON",
        "36130": "DIORS"
        "36200": "LE MENOUX",
        "36260": "REUILLY",
        "36360": "FAVEROLLES SUR CHER",
        "36400": "NERET"
        "36400": "NERET",
        "36600": "FONTGUENAND",
        "36600": "LA VERNELLE",
        "36600": "LYE",
        "36600": "VEUIL",
        "36600": "VILLENTROIS",
        "37000": "TOURS",
        "37120": "CHAVEIGNES",
        "37120": "LA TOUR ST GELIN",
        "37130": "CHAMBOURG SUR INDRE",
        "37130": "CINQ MARS LA PILE",
        "37130": "LIGNIERES DE TOURAINE",
        "37130": "SAINT PATRICE",
        "37140": "BENAIS",
        "37140": "BOURGUEIL",
        "37140": "CHOUZE SUR LOIRE",
        "37140": "INGRANDES DE TOURAINE",
        "37140": "LA CHAPELLE SUR LOIRE",
        "37140": "RESTIGNE",
        "37140": "SAINT NICOLAS DE BOURGUEIL",
        "37150": "BLERE",
        "37150": "CHENONCEAUX",
        "37150": "CHISSEAUX",
        "37150": "CIVRAY DE TOURAINE",
        "37150": "DIERRE",
        "37150": "EPEIGNE LES BOIS",
        "37150": "FRANCUEIL",
        "37150": "LA CROIX EN TOURAINE",
        "37150": "LUZILLE",
        "37150": "SAINT PATRICE",
        "37190": "AZAY LE RIDEAU",
        "37190": "RIVARENNES",
        "37210": "CHANCAY",
        "37210": "NOIZAY",
        "37210": "ROCHECORBON",
        "37210": "SAZILLY",
        "37210": "VERNOU SUR BRENNE",
        "37210": "VOUVRAY"
        "37210": "VOUVRAY",
        "37220": "AVON LES ROCHES",
        "37220": "BRIZAY",
        "37220": "CHEZELLES",
        "37220": "CRISSAY SUR MANSE",
        "37220": "CROUZILLES",
        "37220": "PANZOULT",
        "37220": "TAVANT",
        "37230": "FONDETTES",
        "37240": "VOUVRAY",
        "37270": "ATHEE SUR CHER",
        "37270": "AZAY SUR CHER",
        "37270": "MONTLOUIS SUR LOIRE",
        "37270": "SAINT MARTIN LE BEAU",
        "37270": "VERETZ",
        "37290": "BOUSSAY",
        "37300": "JOUE LES TOURS",
        "37310": "CHAMBOURG SUR INDRE",
        "37310": "SUBLAINES",
        "37320": "ESVRES",
        "37400": "AMBOISE",
        "37400": "LUSSAULT SUR LOIRE",
        "37402": "AMBOISE",
        "37420": "BEAUMONT EN VERON",
        "37420": "HUISMES",
        "37420": "RIGNY USSE",
        "37420": "SAVIGNY EN VERON",
        "37460": "CHEMILLE SUR INDROIS",
        "37460": "GENILLE",
        "37460": "MONTRESOR",
        "37500": "ANCHE",
        "37500": "CANDES SAINT MARTIN",
        "37500": "CHINON",
        "37500": "CRAVANT LES COTEAUX",
        "37500": "LIGRE",
        "37500": "SAINT GERMAIN SUR VIENNE",
        "37500": "SEUILLY",
        "37510": "BALLAN MIRE",
        "37530": "CANGEY",
        "37530": "CHARGE",
        "37530": "LIMERAY",
        "37530": "MOSNES",
        "37530": "NAZELLES NEGRON",
        "37530": "POCE SUR CISSE",
        "37530": "SAINT OUEN LES VIGNES",
        "37600": "LOCHES",
        "37600": "SAINT JEAN SAINT GERMAIN",
        "37790": "VALLERES",
        "37800": "SAINTE MAURE DE TOURAINE",
        "41000": "BLOIS",
        "41100": "MARCILLY EN BEAUCE",
        "41100": "MAZANGE",
        "41100": "NAVEIL",
        "41100": "THORE LA ROCHETTE",
        "41100": "VENDOME",
        "41100": "VILIERS SUR LOIR",
        "41100": "VILLIERS SUR LOIR",
        "41110": "CHATEAUVIEUX",
        "41110": "COUFFY",
        "41110": "MAREUIL SUR CHER",
        "41110": "POUILLE",
        "41110": "SAINT AIGNAN SUR CHER",
        "41110": "SEIGY",
        "41111": "0	SAINT AIGNAN SUR CHER",
        "41120": "CANDE SUR BEUVRON",
        "41120": "CELLETTES",
        "41120": "CHITENAY",
        "41120": "FEINGS",
        "41120": "FOUGERES SUR BIEVRE",
        "41120": "MONTHOU SUR BIEVRE",
        "41120": "OUCHAMPS",
        "41120": "SAMBIN",
        "41120": "VALAIRE",
        "41130": "BILLY",
        "41130": "CHATILLON SUR CHER",
        "41130": "MEUSNES",
        "41130": "SELLES SUR CHER",
        "41140": "MEHERS",
        "41140": "NOYERS SUR CHER",
        "41140": "SAINT ROMAIN SUR CHER"
        "41140": "SAINT ROMAIN SUR CHER",
        "41140": "THESEE",
        "41146": "MONTHOU SUR CHER",
        "41150": "MESLAND",
        "41150": "MONTEAUX",
        "41150": "ONZAIN",
        "41150": "RILLY SUR LOIRE",
        "41180": "MESLAND",
        "41200": "ROMORANTIN LANTHENAY",
        "41230": "GY EN SOLOGNE",
        "41230": "ROUGEOU",
        "41230": "SOING EN SOLOGNE",
        "41230": "SOINGS EN SOLOGNE",
        "41250": "CHAMBORD",
        "41250": "MASLIVES",
        "41250": "MONT PRES CHAMBORD"
        "41250": "MONT PRES CHAMBORD",
        "41350": "HUISSEAU SUR COSSON",
        "41350": "MONTLIVAULT",
        "41350": "SAINT CLAUDE DE DIRAY",
        "41350": "VINEUIL",
        "41360": "LUNAY",
        "41400": "ANGE SUR CHER",
        "41400": "BOURRE",
        "41400": "CHISSAY EN TOURAINE",
        "41400": "FAVEROLLES SUR CHER",
        "41400": "MONTHOU SUR CHER",
        "41400": "MONTRICHARD",
        "41400": "PONTLEVOY",
        "41400": "SAINT GEORGES SUR CHER",
        "41400": "SAINT JULIEN DE CHEDON",
        "41400": "THENAY",
        "41500": "MUIDES SUR LOIRE",
        "41700": "CHEMERY",
        "41700": "CHEVERNY",
        "41700": "CHOUSSY",
        "41700": "CONTRES",
        "41700": "COUDDES",
        "41700": "COUR CHEVERNY",
        "41700": "FRESNES",
        "41700": "OISLY",
        "41700": "SASSAY",
        "41720": "CHEVERNY",
        "41800": "HOUSSAY",
        "41800": "MONTOIRE SUR LE LOIR",
        "41800": "SAINT RIMAY",
        "44000": "NANTES",
        "44115": "HAUTE GOULAINE",
        "44116": "VIEILLEVIGNE",
        "44118": "LA CHEVROLIERE",
        "44120": "VERTOU",
        "44140": "AIGREFEUILLE SUR MAINE",
        "44140": "MONTBERT",
        "44140": "REMOUILLE",
        "44150": "ANCENIS",
        "44150": "ANETZ",
        "44150": "SAINT GEREON",
        "44190": "CLISSON",
        "44190": "GETIGNE",
        "44190": "GORGES",
        "44190": "SAINT HILAIRE DE CLISSON",
        "44190": "SAINT LUMINE DE CLISSON",
        "44196": "SAINT LUMINE DE CLISSON",
        "44310": "LA LIMOUZINIERE",
        "44310": "SAINT COLOMBAN",
        "44310": "SAINT PHILBERT DE GRAND LIEU",
        "44310": "SAINT PHILBERT DE GRANDLIEU",
        "44330": "LA CHAPELLE HEULIN",
        "44330": "LA REGRIPPIERE",
        "44330": "LE LOROUX BOTTEREAU",
        "44330": "LE PALLET",
        "44330": "MOUZILLON",
        "44330": "SAINT PHILBERT DE GRAND LIEU",
        "44330": "VALLET",
        "44412": "REZE",
        "44430": "LA BOISSIERE DU DORE",
        "44430": "LA REMAUDIERE",
        "44430": "LE LANDREAU",
        "44430": "LE LOROUX BOTTEREAU"
        "44430": "LE LOROUX BOTTEREAU",
        "44450": "BARBECHAT",
        "44450": "LA CHAPELLE BASSE MER",
        "44450": "SAINT JULIEN DE CONCELLES",
        "44470": "SAINT JULIEN DE CONCELLES",
        "44521": "OUDON",
        "44580": "BOURGNEUF EN RETZ",
        "44650": " "44330": "CORCOUE SUR LOGNE VALLET",
        "44650": "CORCOUE SUR LOGNE",
        "44650": "LEGE",
        "44680": "CHEMERE",
        "44680": "SAINTE PAZANNE",
        "44680": "SAINT HILAIRE DE CHALEONS",
        "44680": "SAINT MARS DE COUTAIS",
        "44690": "CHATEAU THEBAUD",
        "44690": "CHÂTEAU - THEBAUD",
        "44690": "CHÂTEAU THEBAUD",
        "44690": "LA HAIE FOUASSIERE",
        "44690": "LA HAYE FOUASSIERE",
        "44690": "MAISDON SUR SEVRE",
        "44690": "MONNIERES",
        "44690": "SAINT FIACRE SUR MAINE",
        "44710": "PORT ST PERE",
        "44710": "PORT ST PÈRE",
        "44710": "SAINT LEGER LES VIGNES",
        "44760": "LES MOUTIERS EN RETZ",
        "44830": "BOUAYE",
        "44830": "BRAINS",
        "44850": "LE CELLIER",
        "44850": "LIGNE",
        "44860": "PONT ST MARTIN",
        "44860": "SAINT AIGNAN GRANDLIEU",
        "45000": "ORLEANS",
        "45160": "SAINT HILAIRE SAINT MESMIN",
        "45370": "CLERY ST ANDRE",
        "45370": "MAREAU AUX PRES",
        "45370": "MEZIERES LES CLERY",
        "45400": "FLEURY LES AUBRAIS",
        "45420": "BONNY SUR LOIRE",
        "45430": "CHECY",
        "45480": "JOUY - EN - PITHIVERAIS",
        "45500": "SAINT BRISSON SUR LOIRE",
        "45630": "BEAULIEU SUR LOIRE",
        "49000": "ANGERS",
        "49080": "BOUCHEMAINE",
        "49100": "ANGERS",
        "49110": "SAINT REMY EN MAUGES",
        "49120": "CHANZEAUX",
        "49120": "LA JUMELLIERE",
        "49130": "SAINTE GEMMES SUR LOIRE",
        "49140": "LUE EN BAUGEOIS",
        "49150": "LE VIEIL BAUGE",
        "49170": "LA POSSONNIERE",
        "49170": "SAINT GEORGES SUR LOIRE",
        "49170": "SAVENNIERES",
        "49190": "DENEE",
        "49190": "ROCHEFORT SUR LOIRE",
        "49190": "SAINT AUBIN DE LUIGNE",
        "49230": "SAINT CRESPIN SUR MOINE",
        "49230": "SAINT GERMAIN SUR MOINE",
        "49230": "SEVREMOINE",
        "49230": "ST CRESPIN SUR MOINE",
        "49230": "TILLIERES",
        "49250": "BEAUFORT EN VALLEE",
        "49250": "SAINT REMY LA VARENNE",
        "49260": "ARTANNES SUR THOUET",
        "49260": "BREZE",
        "49260": "COURCHAMPS",
        "49260": "EPIEDS",
        "49260": "LE COUDRAY MACOUARD",
        "49260": "LE PUY NOTRE DAME",
        "49260": "MONTREUIL BELLAY",
        "49260": "SAINT CYR EN BOURG",
        "49260": "SAINT JUST SUR DIVE",
        "49260": "SAINT MACAIRE DU BOIS",
        "49260": "VAUDELNAY",
        "49270": "CHAMPTOCEAUX",
        "49270": "LANDEMONT",
        "49270": "LA VARENNE",
        "49270": "SAINT CHRISTOPHE LA COUPERIE",
        "49270": "SAINT LAURENT DES AUTELS",
        "49270": "SAINT SAUVEUR DE LANDEMONT",
        "49280": "LA SEGUINIERE",
        "49290": "CHALONNES SUR LOIRE",
        "49290": "CHAUDEFONDS SUR LAYON",
        "49310": "CERNUSSON",
        "49310": "LES CERQUEUX SOUS PASSAVANT",
        "49310": "MONTILLIERS",
        "49310": "SAINT CRESPIN SUR MOINE",
        "49310": "SAINT HILAIRE DU BOIS",
        "49310": "TANCOIGNE",
        "49310": "TREMONT",
        "49310": "VIHIERS",
        "49320": "BLAISON GOHIER",
        "49320": "BRISSAC QUINCE",
        "49320": "CHARCE SAINT ELLIER SUR AUBANCE",
        "49320": "COUTURES",
        "49320": "GREZILLE",
        "49320": "LES ALLEUDS",
        "49320": "LUIGNE",
        "49320": "SAINT JEAN DES MAUVRETS",
        "49320": "SAINT SATURNIN SUR LOIRE",
        "49320": "SAULGE L HOPITAL",
        "49320": "VAUCHRETIEN",
        "49350": "CHENEHUTTE",
        "49350": "GENNES",
        "49350": "LE THOUREIL",
        "49350": "SAINT GEORGES DES SEPT VOIES",
        "49370": "SAINT CLEMENT DE LA PLACE",
        "49380": "CHAMP SUR LAYON",
        "49380": "CHAVAGNES LES EAUX",
        "49380": "FAVERAYE MACHELLES",
        "49380": "FAYE D ANJOU",
        "49380": "NOTRE DAME D ALLENCON",
        "49380": "ROCHEFORT SUR LOIRE",
        "49380": "THOUARCE",
        "49400": "CHACE",
        "49400": "DAMPIERRE SUR LOIRE",
        "49400": "DISTRE",
        "49400": "LES ULMES",
        "49400": "ROU MARSON",
        "49400": "SAINT LAMBERT DES LEVEES",
        "49400": "SAUMUR",
        "49400": "SOUZAY CHAMPIGNY",
        "49400": "VARRAINS",
        "49400": "VERRIE",
        "49410": "LA CHAPELLE SAINT FLORENT",
        "49410": "LE MESNIL EN VALLEE",
        "49410": "SAINT FLORENT LE VIEIL",
        "49426": "SAUMUR",
        "49430": "HUILLE",
        "49530": "BOUZILLE",
        "49530": "DRAIN",
        "49530": "LIRE",
        "49540": "AUBIGNE SUR LAYON",
        "49540": "LA FOSSE DE TIGNE",
        "49540": "MARTIGNE BRIAND",
        "49540": "TIGNE",
        "49560": "CLERE SUR LAYON",
        "49560": "NUEIL SUR LAYON",
        "49560": "PASSAVANT SUR LAYON",
        "49570": "MONTJEAN SUR LOIRE",
        "49590": "FONTEVRAUD L ABBAYE",
        "49600": "GESTE",
        "49600": "LA CHAUSSAIRE",
        "49600": "LE PUISET DORE",
        "49610": "JUIGNE SUR LOIRE",
        "49610": "MOZE SUR LOUET",
        "49610": "MURS ERIGNE",
        "49610": "SAINT MELAINE SUR AUBANCE",
        "49610": "SOULAINES SUR AUBANCE",
        "49620": "LA POMMERAYE",
        "49650": "BRAIN SUR ALLONNES",
        "49670": "VALANJOU",
        "49700": "AMBILLOU CHATEAU",
        "49700": "BRIGNE",
        "49700": "BROSSAY",
        "49700": "CIZAY LA MADELEINE",
        "49700": "CONCOURSON SUR LAYON",
        "49700": "DENEZE SOUS DOUE",
        "49700": "DOUE LA FONTAINE",
        "49700": "FORGES",
        "49700": "LES ULMES",
        "49700": "LES VERCHERS SUR LAYON",
        "49700": "LOURESSE ROCHEMENIER",
        "49700": "MEIGNE",
        "49700": "MONTFORT",
        "49700": "SAINT GEORGES SUR LAYON",
        "49730": "MONTSOREAU",
        "49730": "PARNAY",
        "49730": "TURQUANT",
        "49730": "VARENNES SUR LOIRE",
        "49750": "BEAULIEU SUR LAYON",
        "49750": "CHANZEAUX",
        "49750": "RABLAY SUR LAYON",
        "49750": "SAINT LAMBERT DU LATTAY",
        "51380": "VERZY",
        "53940": "SAINT BERTHEVIN",
        "58130": "URZY",
        "58150": "POUILLY SUR LOIRE",
        "58150": "SAINT ANDELAIN",
        "58150": "SAINT MARTIN SUR NOHAIN",
        "58150": "SAINT QUENTIN SUR NOHAIN",
        "58150": "ST LAURENT DE L'ABBAYE",
        "58150": "TRACY SUR LOIRE",
        "58190": "AMAZY",
        "58190": "ASNOIS",
        "58190": "METZ LE COMTE",
        "58190": "TANNAY",
        "58190": "VIGNOL"
        "58200": "ALLIGNY COSNE",
        "58200": "COSNE SUR LOIRE",
        "58200": "POUGNY",
        "58200": "SAINT PERE"
        "58200": "SAINT PÈRE",
        "58210": "MARCY",
        "58240": "LIVRY",
        "58310": "SAINT AMAND EN PUISAYE",
        "58350": "ARBOURSE",
        "58350": "CHASNAY",
        "58400": "CHAULGNES",
        "58400": "RAVEAU",
        "58400": "VARENNES LES NARCY",
        "58420": "BRINON SUR BEUVRON",
        "58500": "VILLIERS SUR YONNE",
        "58700": "LA CELLE SUR NIEVRE",
        "62500": "SAINT MARTIN AU LAERT",
        "67290": "PETERSBACH",
        "69220": "SAINT JEAN D ARDIERES",
        "69220": "SAINT JEAN D'ARDIERES",
        "69800": "SAINT PRIEST",
        "71570": "ROMANECHE-THORINS",
        "72200": "LA FLECHE",
        "72250": "PARIGNE L'EVEQUE",
        "72300": "PARCE SUR SARTHE",
        "72340": "CHAHAIGNES",
        "72340": "LA CHARTRE SUR LE LOIR",
        "72340": "LHOMME"
        "72340": "MARCON",
        "72340": "PONCE SUR LE LOIR",
        "72340": "RUILLE SUR LOIR",
        "72600": "MAMERS",
        "72600": "SAINT LONGIS",
        "75003": "PARIS",
        "75013": "PARIS 13",
        "75014": "PARIS 14",
        "75015": "PARIS 15",
        "75018": "PARIS 18",
        "75019": "PARIS",
        "75116": "PARIS",
        "75116": "PARIS 16",
        "78400": "CHATOU",
        "79100": "MAUZE THOUARSAIS",
        "79100": "OIRON",
        "79100": "SAINT CYR LA LANDE",
        "79100": "SAINTE RADEGONDE",
        "79100": "SAINTE VERGE",
        "79100": "THOUARS",
        "79100": "TOURTENAY",
        "79230": "PRAHECQ",
        "79290": "BAGNEUX",
        "79290": "BOUILLE LORETZ",
        "79290": "BOUILLE SAINT PAUL",
        "79290": "BRION PRES THOUET",
        "79290": "CERSAY",
        "79290": "SAINT MARTIN DE SANZAY",
        "79290": "SAINT PIERRE A CHAMP",
        "79390": "DOUX",
        "80170": "BAYONVILLERS",
        "85110": "CHANTONNAY",
        "85114": "JARD SUR MER",
        "85190": "AIZENAY",
        "85200": "BOURNEAU",
        "85200": "PISSOTTE"
        "85220": "COEX",
        "85310": "CHAILLE S/ ORMEAUX",
        "85310": "LE TABLIER",
        "85310": "SAINT FLORENT DES BOIS",
        "85320": "CHATEAU-GUIBERT",
        "85320": "LA COUTURE",
        "85320": "MAREUIL SUR LAY DISSAIS",
        "85320": "ROSNAY",
        "85340": "OLONNE SUR MER",
        "85440": "TALMONT ST HILAIRE",
        "85470": "BREM SUR MER",
        "85600": "SAINT HILAIRE DE LOULAY",
        "85660": "SAINT PHILBERT DE BOUAINE",
        "85670": "SAINT ETIENNE DU BOIS",
        "85700": "SAINT MESMIN",
        "85770": "VIX",
        "86110": "AMBERRE",
        "86110": "CHOUPPES",
        "86110": "MAZEUIL",
        "86110": "MIREBEAU",
        "86110": "SAINT MARTIN LA PALLU",
        "86110": "THURAGEAU",
        "86110": "VARENNES",
        "86120": "BERRIE",
        "86120": "CURCAY SUR DIVE",
        "86120": "LES TROIS MOUTIERS",
        "86120": "MORTON",
        "86120": "POUANCAY",
        "86120": "SAINT LEGER DE MONTBRILLAIS",
        "86120": "SAIX",
        "86120": "TERNAY",
        "86130": "JAUNAY CLAN",
        "86130": "JAUNAY MARIGNY",
        "86140": "LENCLOITRE",
        "86150": "LE VIGEANT",
        "86170": "BLASLAY",
        "86170": "CHAMPIGNY LE SEC",
        "86170": "CHARRAIS",
        "86170": "CHERVES",
        "86170": "LE ROCHEREAU",
        "86170": "MAISONNEUVE",
        "86170": "MASSOGNES",
        "86170": "NEUVILLE DE POITOU",
        "86170": "VOUZAILLES",
        "86200": "LOUDUN",
        "86380": "CHABOURNAY",
        "86380": "JAUNAY MARIGNY",
        "86380": "MARIGNY BRIZAY",
        "86380": "OUZILLY",
        "86380": "VENDEUVRE DU POITOU",
        "86490": "BEAUMONT",
        "86530": "NAINTRE",
        "89800": "MALIGNY",
