all:
  configuration:
    communes:
      insee2secteur:
        06158: "ALPES MARITIMES	"
        09122: "ARIEGE"
        12066: "AVEYRON"
        12070: "AVEYRON"
        12076: "AVEYRON"
        12086: "AVEYRON"
        12090: "AVEYRON"
        12111: "AVEYRON"
        12149: "AVEYRON"
        12160: "AVEYRON"
        12200: "AVEYRON"
        12233: "AVEYRON"
        15113: "CANTAL"
        15119: "CANTAL"
        15127: "CANTAL"
        31038: "HAUTE-GARONNE"
        31052: "HAUTE-GARONNE"
        31065: "HAUTE-GARONNE"
        31079: "HAUTE-GARONNE"
        31093: "HAUTE-GARONNE"
        31101: "HAUTE-GARONNE"
        31118: "HAUTE-GARONNE"
        31202: "HAUTE-GARONNE"
        31232: "HAUTE-GARONNE"
        31286: "HAUTE-GARONNE"
        31287: "HAUTE-GARONNE"
        31383: "HAUTE-GARONNE"
        31399: "HAUTE-GARONNE"
        31416: "HAUTE-GARONNE"
        31459: "HAUTE-GARONNE"
        31476: "HAUTE-GARONNE"
        31515: "HAUTE-GARONNE"
        31555: "HAUTE-GARONNE"
        31560: "HAUTE-GARONNE"
        31563: "HAUTE-GARONNE"
        31581: "HAUTE-GARONNE"
        31583: "HAUTE-GARONNE"
        31584: "HAUTE-GARONNE"
        31587: "HAUTE-GARONNE"
        40013: "LANDES"
        40016: "LANDES"
        40024: "LANDES"
        40035: "LANDES"
        40039: "LANDES"
        40052: "LANDES"
        40078: "LANDES"
        40082: "LANDES"
        40083: "LANDES"
        40086: "LANDES"
        40091: "LANDES"
        40097: "LANDES"
        40100: "LANDES"
        40102: "LANDES"
        40110: "LANDES"
        40118: "LANDES"
        40127: "LANDES"
        40131: "LANDES"
        40137: "LANDES"
        40140: "LANDES"
        40145: "LANDES"
        40176: "LANDES"
        40181: "LANDES"
        40185: "LANDES"
        40188: "LANDES"
        40195: "LANDES"
        40218: "LANDES"
        40219: "LANDES"
        40221: "LANDES"
        40239: "LANDES"
        40253: "LANDES"
        40265: "LANDES"
        40270: "LANDES"
        40298: "LANDES"
        40299: "LANDES"
        40305: "LANDES"
        46001: "LOT"
        46005: "LOT"
        46014: "LOT"
        46022: "LOT"
        46023: "LOT"
        46025: "LOT"
        46033: "LOT"
        46042: "LOT"
        46044: "LOT"
        46050: "LOT"
        46059: "LOT"
        46060: "LOT"
        46063: "LOT"
        46070: "LOT"
        46088: "LOT"
        46089: "LOT"
        46099: "LOT"
        46102: "LOT"
        46103: "LOT"
        46105: "LOT"
        46107: "LOT"
        46124: "LOT"
        46126: "LOT"
        46127: "LOT"
        46130: "LOT"
        46137: "LOT"
        46142: "LOT"
        46156: "LOT"
        46182: "LOT"
        46184: "LOT"
        46187: "LOT"
        46191: "LOT"
        46192: "LOT"
        46197: "LOT"
        46202: "LOT"
        46211: "LOT"
        46214: "LOT"
        46218: "LOT"
        46222: "LOT"
        46224: "LOT"
        46225: "LOT"
        46228: "LOT"
        46231: "LOT"
        46237: "LOT"
        46240: "LOT"
        46247: "LOT"
        46262: "LOT"
        46263: "LOT"
        46268: "LOT"
        46287: "LOT"
        46291: "LOT"
        46296: "LOT"
        46300: "LOT"
        46301: "LOT"
        46305: "LOT"
        46307: "LOT"
        46321: "LOT"
        46322: "LOT"
        46327: "LOT"
        46335: "LOT"
        46336: "LOT"
        47003: "LOT-ET-GARONNE"
        47008: "LOT-ET-GARONNE"
        47011: "LOT-ET-GARONNE"
        47015: "LOT-ET-GARONNE"
        47017: "LOT-ET-GARONNE"
        47018: "LOT-ET-GARONNE"
        47020: "LOT-ET-GARONNE"
        47024: "LOT-ET-GARONNE"
        47038: "LOT-ET-GARONNE"
        47043: "LOT-ET-GARONNE"
        47045: "LOT-ET-GARONNE"
        47046: "LOT-ET-GARONNE"
        47047: "LOT-ET-GARONNE"
        47048: "LOT-ET-GARONNE"
        47049: "LOT-ET-GARONNE"
        47060: "LOT-ET-GARONNE"
        47068: "LOT-ET-GARONNE"
        47076: "LOT-ET-GARONNE"
        47077: "LOT-ET-GARONNE"
        47081: "LOT-ET-GARONNE"
        47086: "LOT-ET-GARONNE"
        47088: "LOT-ET-GARONNE"
        47089: "LOT-ET-GARONNE"
        47090: "LOT-ET-GARONNE"
        47097: "LOT-ET-GARONNE"
        47103: "LOT-ET-GARONNE"
        47104: "LOT-ET-GARONNE"
        47115: "LOT-ET-GARONNE"
        47124: "LOT-ET-GARONNE"
        47126: "LOT-ET-GARONNE"
        47131: "LOT-ET-GARONNE"
        47132: "LOT-ET-GARONNE"
        47133: "LOT-ET-GARONNE"
        47134: "LOT-ET-GARONNE"
        47137: "LOT-ET-GARONNE"
        47143: "LOT-ET-GARONNE"
        47145: "LOT-ET-GARONNE"
        47151: "LOT-ET-GARONNE"
        47152: "LOT-ET-GARONNE"
        47156: "LOT-ET-GARONNE"
        47157: "LOT-ET-GARONNE"
        47165: "LOT-ET-GARONNE"
        47166: "LOT-ET-GARONNE"
        47167: "LOT-ET-GARONNE"
        47169: "LOT-ET-GARONNE"
        47170: "LOT-ET-GARONNE"
        47174: "LOT-ET-GARONNE"
        47175: "LOT-ET-GARONNE"
        47176: "LOT-ET-GARONNE"
        47177: "LOT-ET-GARONNE"
        47178: "LOT-ET-GARONNE"
        47180: "LOT-ET-GARONNE"
        47186: "LOT-ET-GARONNE"
        47187: "LOT-ET-GARONNE"
        47191: "LOT-ET-GARONNE"
        47195: "LOT-ET-GARONNE"
        47197: "LOT-ET-GARONNE"
        47199: "LOT-ET-GARONNE"
        47202: "LOT-ET-GARONNE"
        47207: "LOT-ET-GARONNE"
        47211: "LOT-ET-GARONNE"
        47221: "LOT-ET-GARONNE"
        47224: "LOT-ET-GARONNE"
        47229: "LOT-ET-GARONNE"
        47230: "LOT-ET-GARONNE"
        47233: "LOT-ET-GARONNE"
        47236: "LOT-ET-GARONNE"
        47238: "LOT-ET-GARONNE"
        47239: "LOT-ET-GARONNE"
        47246: "LOT-ET-GARONNE"
        47247: "LOT-ET-GARONNE"
        47252: "LOT-ET-GARONNE"
        47253: "LOT-ET-GARONNE"
        47258: "LOT-ET-GARONNE"
        47259: "LOT-ET-GARONNE"
        47264: "LOT-ET-GARONNE"
        47266: "LOT-ET-GARONNE"
        47267: "LOT-ET-GARONNE"
        47275: "LOT-ET-GARONNE"
        47277: "LOT-ET-GARONNE"
        47278: "LOT-ET-GARONNE"
        47281: "LOT-ET-GARONNE"
        47282: "LOT-ET-GARONNE"
        47290: "LOT-ET-GARONNE"
        47294: "LOT-ET-GARONNE"
        47295: "LOT-ET-GARONNE"
        47301: "LOT-ET-GARONNE"
        47302: "LOT-ET-GARONNE"
        47303: "LOT-ET-GARONNE"
        47307: "LOT-ET-GARONNE"
        47318: "LOT-ET-GARONNE"
        47320: "LOT-ET-GARONNE"
        47321: "LOT-ET-GARONNE"
        47326: "LOT-ET-GARONNE"
        47327: "LOT-ET-GARONNE"
        47328: "LOT-ET-GARONNE"
        47340: "LOT-ET-GARONNE"
        64056: "PYRENEES-ATLANTIQUE"
        64074: "PYRENEES-ATLANTIQUE"
        64075: "PYRENEES-ATLANTIQUE"
        64079: "PYRENEES-ATLANTIQUE"
        64084: "PYRENEES-ATLANTIQUE"
        64118: "PYRENEES-ATLANTIQUE"
        64158: "PYRENEES-ATLANTIQUE"
        64159: "PYRENEES-ATLANTIQUE"
        64180: "PYRENEES-ATLANTIQUE"
        64192: "PYRENEES-ATLANTIQUE"
        64196: "PYRENEES-ATLANTIQUE"
        64197: "PYRENEES-ATLANTIQUE"
        64198: "PYRENEES-ATLANTIQUE"
        64199: "PYRENEES-ATLANTIQUE"
        64202: "PYRENEES-ATLANTIQUE"
        64236: "PYRENEES-ATLANTIQUE"
        64283: "PYRENEES-ATLANTIQUE"
        64284: "PYRENEES-ATLANTIQUE"
        64323: "PYRENEES-ATLANTIQUE"
        64324: "PYRENEES-ATLANTIQUE"
        64359: "PYRENEES-ATLANTIQUE"
        64365: "PYRENEES-ATLANTIQUE"
        64366: "PYRENEES-ATLANTIQUE"
        64373: "PYRENEES-ATLANTIQUE"
        64390: "PYRENEES-ATLANTIQUE"
        64393: "PYRENEES-ATLANTIQUE"
        64394: "PYRENEES-ATLANTIQUE"
        64401: "PYRENEES-ATLANTIQUE"
        64455: "PYRENEES-ATLANTIQUE"
        64486: "PYRENEES-ATLANTIQUE"
        64534: "PYRENEES-ATLANTIQUE"
        82002: "TARN-ET-GARONNE"
        82008: "TARN-ET-GARONNE"
        82009: "TARN-ET-GARONNE"
        82013: "TARN-ET-GARONNE"
        82014: "TARN-ET-GARONNE"
        82017: "TARN-ET-GARONNE"
        82020: "TARN-ET-GARONNE"
        82023: "TARN-ET-GARONNE"
        82024: "TARN-ET-GARONNE"
        82025: "TARN-ET-GARONNE"
        82026: "TARN-ET-GARONNE"
        82027: "TARN-ET-GARONNE"
        82028: "TARN-ET-GARONNE"
        82030: "TARN-ET-GARONNE"
        82031: "TARN-ET-GARONNE"
        82032: "TARN-ET-GARONNE"
        82033: "TARN-ET-GARONNE"
        82034: "TARN-ET-GARONNE"
        82037: "TARN-ET-GARONNE"
        82042: "TARN-ET-GARONNE"
        82048: "TARN-ET-GARONNE"
        82049: "TARN-ET-GARONNE"
        82050: "TARN-ET-GARONNE"
        82051: "TARN-ET-GARONNE"
        82057: "TARN-ET-GARONNE"
        82067: "TARN-ET-GARONNE"
        82075: "TARN-ET-GARONNE"
        82079: "TARN-ET-GARONNE"
        82080: "TARN-ET-GARONNE"
        82092: "TARN-ET-GARONNE"
        82093: "TARN-ET-GARONNE"
        82096: "TARN-ET-GARONNE"
        82105: "TARN-ET-GARONNE"
        82108: "TARN-ET-GARONNE"
        82112: "TARN-ET-GARONNE"
        82113: "TARN-ET-GARONNE"
        82115: "TARN-ET-GARONNE"
        82117: "TARN-ET-GARONNE"
        82119: "TARN-ET-GARONNE"
        82121: "TARN-ET-GARONNE"
        82123: "TARN-ET-GARONNE"
        82128: "TARN-ET-GARONNE"
        82130: "TARN-ET-GARONNE"
        82131: "TARN-ET-GARONNE"
        82135: "TARN-ET-GARONNE"
        82136: "TARN-ET-GARONNE"
        82142: "TARN-ET-GARONNE"
        82144: "TARN-ET-GARONNE"
        82145: "TARN-ET-GARONNE"
        82148: "TARN-ET-GARONNE"
        82156: "TARN-ET-GARONNE"
        82158: "TARN-ET-GARONNE"
        82166: "TARN-ET-GARONNE"
        82168: "TARN-ET-GARONNE"
        82173: "TARN-ET-GARONNE"
        82176: "TARN-ET-GARONNE"
        82177: "TARN-ET-GARONNE"
        82178: "TARN-ET-GARONNE"
        82180: "TARN-ET-GARONNE"
        82184: "TARN-ET-GARONNE"
        82186: "TARN-ET-GARONNE"
        82189: "TARN-ET-GARONNE"
        82190: "TARN-ET-GARONNE"
        82193: "TARN-ET-GARONNE"
        82194: "TARN-ET-GARONNE"
