all:
  configuration:
    degustation:
      colleges:
        degustateur_technicien: "Techniciens"
        degustateur_operateur: "Opérateurs"
        degustateur_usager_du_produit: "Usagers du produit"
      anonymat4labo: true
      conformite:
        - CONFORME
        - NONCONFORME_MINEUR
        - NONCONFORME_MAJEUR
        - NONCONFORME_MAJEUR_CONDITIONNÉ
        - NONCONFORME_GRAVE
        - NONTYPICITE_CEPAGE
        - NONCONFORME_ANALYTIQUE
      has_notification: true
      always_identifiant_table: true
      tournees_par_secteur: true
