all:
  configuration:
    communes:
      insee2commune:
        "84003": "APT"
        "84004": "AUBIGNAN"
        "84008": "LE BARROUX"
        "84011": "BEAUCET"
        "84015": "BEAUMONT-DU-VENTOUX"
        "84017": "BEDOIN"
        "84018": "BLAUVAC"
        "84020": "BONNIEUX"
        "84025": "CABRIERES-D'AVIGNON"
        "84030": "CAROMB"
        "84031": "CARPENTRAS"
        "84032": "CASENEUVE"
        "84040": "CRESTET"
        "84041": "CRILLON-LE-BRAVE"
        "84044": "ENTRECHAUX"
        "84046": "FLASSAN"
        "84047": "GARGAS"
        "84048": "GIGNAC"
        "84050": "GORDES"
        "84051": "GOULT"
        "84057": "JOUCAS"
        "84062": "LAGNES"
        "84066": "LIOUX"
        "84067": "LORIOL-DU-COMTAT"
        "84069": "MALAUCENE"
        "84070": "MALEMORT-DU-COMTAT"
        "84072": "MAZAN"
        "84075": "METHAMIS"
        "84077": "MODENE"
        "84082": "MORMOIRON"
        "84085": "MURS"
        "84088": "PERNES-LES-FONTAINES"
        "84099": "ROBION"
        "84101": "LA ROQUE-SUR-PERNES"
        "84102": "ROUSSILLON"
        "84103": "RUSTREL"
        "84105": "SAIGNON"
        "84108": "SAINT-DIDIER"
        "84109": "SAINT-HIPPOLYTE-LE-GRAVEYRON"
        "84112": "SAINT-MARTIN-DE-CASTILLON"
        "84114": "SAINT-PANTALEON"
        "84115": "SAINT-PIERRE-DE-VASSOLS"
        "84118": "SAINT-SATURNIN-LES-APT"
        "84124": "SAUMANE-DE-VAUCLUSE"
        "84143": "VENASQUE"
        "84144": "VIENS"
        "84145": "VILLARS"
        "84148": "VILLES-SUR-AUZON"
