all:
  configuration:
    facture:
      echeances: false
      modalite_paiement: "- comptant par virement \\ - comptant par chèque \\ - paiement à réception de facture \\"
      uniq_template_prefix: "TEMPLATE-FACTURE"
      paiements: true
      exercice: 'recolte'
      liste_dernier_exercice: true
