all:
  configuration:
    facture:
      echeances: false
      export_sage_width_txt: true
      modalite_paiement: "30 jour par virement"
      uniq_template_prefix: "TEMPLATE-FACTURE-%region%"
      paiements: true
      export_type: "isa"
      liste_dernier_exercice: true
      facturation_region: true
