all:
  configuration:
    habilitation:
      activites:
         PRODUCTEUR: "Producteur de raisins"
         PRODUCTEUR_MOUTS: "Producteur de moût"
         VINIFICATEUR: "Vinificateur"
         CONDITIONNEUR: "Conditionneur"
         NEGOCIANT: "Négociant"
         VRAC: "Vrac export"
         ELABORATEUR: "Élaboration de Mousseux"
         ELEVEUR: "Élevage"
      demande:
        statuts:
          DEPOT: "Dépôt"
          COMPLET: "Complet"
          ENREGISTREMENT: "Enregistrement"
          TRANSMIS_INAO: "Transmis à QUALISUD"
          VALIDE_INAO: "Validé par QUALISUD"
          REFUSE_INAO: "Refusé par QUALISUD"
          SUSPENDU_INAO: "Suspendu par QUALISUD"
          VALIDE: "Validé"
          REFUSE: "Refusé"
          ANNULE: "Annulé"
          automatique:
            COMPLET: ENREGISTREMENT
            VALIDE_INAO: VALIDE
            REFUSE_INAO: REFUSE
            habilitations:
              HABILITATION:
                COMPLET: DEMANDE_HABILITATION
                VALIDE: HABILITE
                REFUSE: REFUS
                ANNULE: ANNULÉ
                SUSPENDU_INAO: SUSPENDU
                RETRAIT:
                  COMPLET: DEMANDE_RETRAIT
                  VALIDE: RETRAIT
                  REFUSE: HABILITE
                  ANNULE: HABILITE
                  SUSPENDU_INAO: SUSPENDU
                  RESILIATION:
                    COMPLET: DEMANDE_RESILIATION
                    VALIDE: RESILIE
                    REFUSE: HABILITE
                    ANNULE: HABILITE
                    SUSPENDU_INAO: SUSPENDU
