all:
  configuration:
    parcellaire:
      show_filter_produits_configuration: false
      ecart_rangs_max: 250
      ecart_pieds_min:  80
      affectation:
        needs_intention: false
        potentiel_de_production_based: true
      aires:
        Gaillac:
          name: "AOC Gaillac"
          color: "#e58ebc"
          denomination_id: "00093"
        Gaillac-premierescotes:
          name: "AOC Gaillac premières côtes"
          color: "#52e536"
          denomination_id: "00095"
      potentiel_de_production:
        gaillac_blanc:
          synthese_libelle: "AOP Gaillac Blanc sec"
          filter_produit_hash: 'appellations/GLC'
          hash_produit_affectation: 'certifications/AOP/genres/TRANQ/appellations/GLC/mentions/DEFAUT/lieux/DEFAUT/couleurs/blanc_sec/cepages/DEFAUT'
          denomination_aire: "AOC Gaillac"
          parcellaire2reference: 'ParcellaireAffectation'
          categories:
            cepages_principaux: ["LEN DE L'EL B", 'MAUZAC B', 'MAUZAC ROSE RS', 'MUSCADELLE B']
            cepages_accessoires: ['ONDENC B', 'SAUVIGNON B']
          regles:
            -
              fonction: 'ProportionSomme'
              category: 'cepages_couleur'
              sens: ">="
              limit: 1
            -
              fonction: 'ProportionSomme'
              category: 'cepages_principaux'
              sens: ">="
              limit: 0.50
        gaillac_blanc_doux:
          synthese_libelle: "AOP Gaillac Blanc doux"
          filter_produit_hash: 'appellations/GLC'
          hash_produit_affectation: 'certifications/AOP/genres/TRANQ/appellations/GLC/mentions/DEFAUT/lieux/DEFAUT/couleurs/blanc_doux/cepages/DEFAUT'
          denomination_aire: "AOC Gaillac"
          parcellaire2reference: 'ParcellaireAffectation'
          categories:
            cepages_principaux: ["LEN DE L'EL B", 'MAUZAC B', 'MAUZAC ROSE RS', 'MUSCADELLE B']
            cepages_accessoires: ['ONDENC B', 'SAUVIGNON B']
          regles:
            -
              fonction: 'ProportionSomme'
              category: 'cepages_couleur'
              sens: ">="
              limit: 1
            -
              fonction: 'ProportionSomme'
              category: 'cepages_principaux'
              sens: ">="
              limit: 0.50
        gaillac_blanc_primeur:
          synthese_libelle: "AOP Gaillac Primeur Blanc sec"
          filter_produit_hash: 'appellations/GLC'
          hash_produit_affectation: 'certifications/AOP/genres/TRANQ/appellations/GLC/mentions/PM/lieux/DEFAUT/couleurs/blanc_sec/cepages/DEFAUT'
          denomination_aire: "AOC Gaillac"
          parcellaire2reference: 'ParcellaireAffectation'
          categories:
            cepages_principaux: ["LEN DE L'EL B", 'MAUZAC B', 'MAUZAC ROSE RS', 'MUSCADELLE B']
            cepages_accessoires: ['ONDENC B', 'SAUVIGNON B']
          regles:
            -
              fonction: 'ProportionSomme'
              category: 'cepages_couleur'
              sens: ">="
              limit: 1
            -
              fonction: 'ProportionSomme'
              category: 'cepages_principaux'
              sens: ">="
              limit: 0.50
        premiere_blanc:
          synthese_libelle: "AOP Gaillac Premieres Côtes Blanc sec"
          filter_produit_hash: 'appellations/GLC'
          hash_produit_affectation: 'certifications/AOP/genres/TRANQ/appellations/GPC/mentions/DEFAUT/lieux/DEFAUT/couleurs/blanc_sec/cepages/DEFAUT'
          denomination_aire: "AOC Gaillac premières côtes"
          parcellaire2reference: 'ParcellaireAffectation'
          categories:
            cepages_principaux: ["LEN DE L'EL B", 'MAUZAC B', 'MAUZAC ROSE RS', 'MUSCADELLE B']
            cepages_accessoires: ['ONDENC B', 'SAUVIGNON B']
          regles:
            -
              fonction: 'ProportionSomme'
              category: 'cepages_couleur'
              sens: ">="
              limit: 1
            -
              fonction: 'ProportionSomme'
              category: 'cepages_principaux'
              sens: ">="
              limit: 0.50
        gaillac_rouge:
          synthese_libelle: "AOP Gaillac Rouge"
          filter_produit_hash: 'appellations/GLC'
          hash_produit_affectation: 'certifications/AOP/genres/TRANQ/appellations/GLC/mentions/DEFAUT/lieux/DEFAUT/couleurs/rouge/cepages/DEFAUT'
          denomination_aire: "AOC Gaillac"
          parcellaire2reference: 'ParcellaireAffectation'
          categories:
            cepages_principaux: ['DURAS N', 'FER N', 'PRUNELARD N', 'SYRAH N']
            cepages_duras_fer_prunelard: ['DURAS N', 'FER N', 'PRUNELARD N']
            cepages_accessoires: ['CABERNET FRANC N', 'CABERNET-SAUVIGNON N', 'GAMAY N, MERLOT N']
          regles:
            -
              fonction: 'ProportionSomme'
              category: 'cepages_couleur'
              sens: ">="
              limit: 1
            -
              fonction: 'ProportionSomme'
              category: 'cepages_principaux'
              sens: ">="
              limit: 0.70
            -
              fonction: "Nombre"
              category: "cepages_principaux"
              sens: ">="
              limit: 2
            -
              fonction: 'ProportionSomme'
              category: 'cepages_duras_fer_prunelard'
              sens: ">="
              limit: 0.40
        gaillac_rose:
          synthese_libelle: "AOP Gaillac Rosé"
          filter_produit_hash: 'appellations/GLC'
          hash_produit_affectation: 'certifications/AOP/genres/TRANQ/appellations/GLC/mentions/DEFAUT/lieux/DEFAUT/couleurs/rose/cepages/DEFAUT'
          denomination_aire: "AOC Gaillac"
          parcellaire2reference: 'ParcellaireAffectation'
          categories:
            cepages_principaux: ['DURAS N', 'FER N', 'PRUNELARD N', 'SYRAH N']
            cepages_duras_fer_prunelard: ['DURAS N', 'FER N', 'PRUNELARD N']
            cepages_accessoires: ['CABERNET FRANC N', 'CABERNET-SAUVIGNON N', 'GAMAY N, MERLOT N']
          regles:
            -
              fonction: 'ProportionSomme'
              category: 'cepages_couleur'
              sens: ">="
              limit: 1
            -
              fonction: 'ProportionSomme'
              category: 'cepages_principaux'
              sens: ">="
              limit: 0.70
            -
              fonction: "Nombre"
              category: "cepages_principaux"
              sens: ">="
              limit: 2
            -
              fonction: 'ProportionSomme'
              category: 'cepages_duras_fer_prunelard'
              sens: ">="
              limit: 0.40
        gaillac_rouge_primeur:
          synthese_libelle: "AOP Gaillac Primeur Rouge"
          filter_produit_hash: 'appellations/GLC'
          hash_produit_affectation: 'certifications/AOP/genres/TRANQ/appellations/GLC/mentions/PM/lieux/DEFAUT/couleurs/rouge/cepages/DEFAUT'
          denomination_aire: "AOC Gaillac"
          parcellaire2reference: 'ParcellaireAffectation'
          categories:
            cepages_principaux: ['GAMAY N']
          regles:
            -
              fonction: 'ProportionSomme'
              category: 'cepages_couleur'
              sens: ">="
              limit: 1
            -
              fonction: 'ProportionSomme'
              category: 'cepages_principaux'
              sens: ">="
              limit: 1
        gaillac_mousseux_ancestrale:
          synthese_libelle: "AOP Gaillac Mousseux Méthode Ancestrale"
          filter_produit_hash: 'appellations/GLC'
          hash_produit_affectation: 'certifications/AOP/genres/MOU/appellations/GLC/mentions/MA/lieux/DEFAUT/couleurs/blanc/cepages/DEFAUT'
          denomination_aire: "AOC Gaillac"
          parcellaire2reference: 'ParcellaireAffectation'
          categories:
            cepages_principaux: ['MAUZAC B', 'MAUZAC ROSE RS']
          regles:
            -
              fonction: 'ProportionSomme'
              category: 'cepages_couleur'
              sens: ">="
              limit: 1
            -
              fonction: 'ProportionSomme'
              category: 'cepages_principaux'
              sens: ">="
              limit: 1
        gaillac_mousseux_ancestrale_doux:
          synthese_libelle: "AOP Gaillac Mousseux Méthode Ancestrale Doux"
          filter_produit_hash: 'appellations/GLC'
          hash_produit_affectation: 'certifications/AOP/genres/MOU/appellations/GLC/mentions/MA/lieux/DEFAUT/couleurs/blanc_doux/cepages/DEFAUT'
          denomination_aire: "AOC Gaillac"
          parcellaire2reference: 'ParcellaireAffectation'
          categories:
            cepages_principaux: ['MAUZAC B', 'MAUZAC ROSE RS']
          regles:
            -
              fonction: 'ProportionSomme'
              category: 'cepages_couleur'
              sens: ">="
              limit: 1
            -
              fonction: 'ProportionSomme'
              category: 'cepages_principaux'
              sens: ">="
              limit: 1
        gaillac_mousseux_tranditionnel:
          synthese_libelle: "AOP Gaillac Mousseux Méthode Traditionnelle"
          filter_produit_hash: 'appellations/GLC'
          hash_produit_affectation: 'certifications/AOP/genres/MOU/appellations/GLC/mentions/DEFAUT/lieux/DEFAUT/couleurs/blanc/cepages/DEFAUT'
          denomination_aire: "AOC Gaillac"
          parcellaire2reference: 'ParcellaireAffectation'
          categories:
            cepages_principaux: ['MAUZAC B', 'MAUZAC ROSE RS']
          regles:
            -
              fonction: 'ProportionSomme'
              category: 'cepages_couleur'
              sens: ">="
              limit: 1
            -
              fonction: 'ProportionSomme'
              category: 'cepages_principaux'
              sens: ">="
              limit: 1
        gaillac_blanc_tardive:
          synthese_libelle: "AOP Gaillac Blanc doux Vendanges tardives"
          filter_produit_hash: 'appellations/GLC'
          hash_produit_affectation: 'certifications/AOP/genres/TRANQ/appellations/GLC/mentions/VT/lieux/DEFAUT/couleurs/blanc_doux/cepages/DEFAUT'
          denomination_aire: "AOC Gaillac"
          parcellaire2reference: 'ParcellaireAffectation'
          categories:
            cepages_principaux: ["LEN DE L'EL B", "ONDENC B"]
            cepages_secondaires: ["MAUZAC B, MAUZAC ROSE RS, MUSCADELLE B"]
          regles:
            -
              fonction: 'ProportionSomme'
              category: 'cepages_couleur'
              sens: ">="
              limit: 1
            -
              fonction: 'ProportionSomme'
              category: 'cepages_principaux'
              sens: ">="
              limit: 0.50
