all:
  configuration:
    parcellaire:
      show_filter_produits_configuration: false
      ecart_rangs_max: 250
      ecart_pieds_min:  80
      aires:
        communes-aoc:
          name: "AOC Gaillac"
          color: "#e58ebc"
          denomination_id: "00093"
        communes-stevictoire:
          name: "AOC Gaillac premières côtes"
          color: "#52e536"
          denomination_id: "00095"
