all:
  configuration:
    parcellaire:
      show_filter_produits_configuration: false
      ecart_rangs_max: 250
      ecart_pieds_min:  80
      affectation:
        needs_intention: false
        potentiel_de_production_based: true
      aires:
        Gaillac:
          name: "AOC Gaillac"
          color: "#e58ebc"
          denomination_id: "00093"
        Gaillac-premierescotes:
          name: "AOC Gaillac premières côtes"
          color: "#52e536"
          denomination_id: "00095"
      potentiel_de_production:
        gaillac_blanc:
          synthese_libelle: "Gaillac - Blanc sec"
          filter_parcellaire_produit_hash: 'appellations/GLC'
          produit_hash: 'certifications/AOP/genres/TRANQ/appellations/GLC/mentions/DEFAUT/lieux/DEFAUT/couleurs/blanc_sec/cepages/DEFAUT'
          has_affectation: true
          denomination_aire: "AOC Gaillac"
          parcellaire2reference: 'ParcellaireAffectation'
          categories:
            cepages_principaux: ["LEN DE L'EL B", 'MAUZAC B', 'MAUZAC ROSE RS', 'MUSCADELLE B']
            cepages_accessoires: ['ONDENC B', 'SAUVIGNON B']
          regles:
            -
              fonction: 'ProportionSomme'
              category: 'cepages_couleur'
              sens: ">="
              limit: 1
            -
              fonction: 'ProportionSomme'
              category: 'cepages_principaux'
              sens: ">="
              limit: 0.50
            -
              fonction: 'ProportionSomme'
              category: 'cepages_accessoires'
              sens: "<="
              limit: 0.50
        gaillac_blanc_doux:
          synthese_libelle: "Gaillac - Blanc doux"
          filter_parcellaire_produit_hash: 'appellations/GLC'
          produit_hash: 'certifications/AOP/genres/TRANQ/appellations/GLC/mentions/DEFAUT/lieux/DEFAUT/couleurs/blanc_doux/cepages/DEFAUT'
          has_affectation: true
          denomination_aire: "AOC Gaillac"
          parcellaire2reference: 'ParcellaireAffectation'
          categories:
            cepages_principaux: ["LEN DE L'EL B", 'MAUZAC B', 'MAUZAC ROSE RS', 'MUSCADELLE B']
            cepages_accessoires: ['ONDENC B', 'SAUVIGNON B']
          regles:
            -
              fonction: 'ProportionSomme'
              category: 'cepages_couleur'
              sens: ">="
              limit: 1
            -
              fonction: 'ProportionSomme'
              category: 'cepages_principaux'
              sens: ">="
              limit: 0.50
            -
              fonction: 'ProportionSomme'
              category: 'cepages_accessoires'
              sens: "<="
              limit: 0.50
        gaillac_blanc_primeur:
          synthese_libelle: "Gaillac - Primeur Blanc sec"
          filter_parcellaire_produit_hash: 'appellations/GLC'
          produit_hash: 'certifications/AOP/genres/TRANQ/appellations/GLC/mentions/PM/lieux/DEFAUT/couleurs/blanc_sec/cepages/DEFAUT'
          has_affectation: true
          denomination_aire: "AOC Gaillac"
          parcellaire2reference: 'ParcellaireAffectation'
          categories:
            cepages_principaux: ["LEN DE L'EL B", 'MAUZAC B', 'MAUZAC ROSE RS', 'MUSCADELLE B']
            cepages_accessoires: ['ONDENC B', 'SAUVIGNON B']
          regles:
            -
              fonction: 'ProportionSomme'
              category: 'cepages_couleur'
              sens: ">="
              limit: 1
            -
              fonction: 'ProportionSomme'
              category: 'cepages_principaux'
              sens: ">="
              limit: 0.50
            -
              fonction: 'ProportionSomme'
              category: 'cepages_accessoires'
              sens: "<="
              limit: 0.50
        premiere_blanc:
          synthese_libelle: "Gaillac - Premieres Côtes Blanc sec"
          filter_parcellaire_produit_hash: 'appellations/GPC'
          produit_hash: 'certifications/AOP/genres/TRANQ/appellations/GPC/mentions/DEFAUT/lieux/DEFAUT/couleurs/blanc_sec/cepages/DEFAUT'
          has_affectation: true
          denomination_aire: "AOC Gaillac premières côtes"
          parcellaire2reference: 'ParcellaireAffectation'
          categories:
            cepages_principaux: ["LEN DE L'EL B", 'MAUZAC B', 'MAUZAC ROSE RS', 'MUSCADELLE B']
            cepages_accessoires: ['ONDENC B', 'SAUVIGNON B']
          regles:
            -
              fonction: 'ProportionSomme'
              category: 'cepages_couleur'
              sens: ">="
              limit: 1
            -
              fonction: 'ProportionSomme'
              category: 'cepages_principaux'
              sens: ">="
              limit: 0.50
            -
              fonction: 'ProportionSomme'
              category: 'cepages_accessoires'
              sens: "<="
              limit: 0.50
        gaillac_rouge:
          synthese_libelle: "Gaillac - Rouge"
          filter_parcellaire_produit_hash: 'appellations/GLC'
          produit_hash: 'certifications/AOP/genres/TRANQ/appellations/GLC/mentions/DEFAUT/lieux/DEFAUT/couleurs/rouge/cepages/DEFAUT'
          has_affectation: true
          denomination_aire: "AOC Gaillac"
          parcellaire2reference: 'ParcellaireAffectation'
          categories:
            cepages_principaux: ['DURAS N', 'FER N', 'PRUNELARD N', 'SYRAH N']
            cepages_duras_fer_prunelard: ['DURAS N', 'FER N', 'PRUNELARD N']
            cepages_secondaires: ['CABERNET-SAUVIGNON N', 'GAMAY N, MERLOT N']
            cepages_accessoires: ['CABERNET FRANC N']
          regles:
            -
              fonction: 'ProportionSomme'
              category: 'cepages_couleur'
              sens: ">="
              limit: 1
            -
              fonction: 'ProportionSomme'
              category: 'cepages_principaux'
              sens: ">="
              limit: 0.70
            -
              fonction: 'ProportionSomme'
              category: 'cepages_duras_fer_prunelard'
              sens: ">="
              limit: 0.40
            -
              fonction: 'ProportionSomme'
              category: 'cepages_secondaires'
              sens: "<="
              limit: 0.30
        gaillac_rose:
          synthese_libelle: "Gaillac - Rosé"
          filter_parcellaire_produit_hash: 'appellations/GLC'
          produit_hash: 'certifications/AOP/genres/TRANQ/appellations/GLC/mentions/DEFAUT/lieux/DEFAUT/couleurs/rose/cepages/DEFAUT'
          has_affectation: true
          denomination_aire: "AOC Gaillac"
          parcellaire2reference: 'ParcellaireAffectation'
          categories:
            cepages_principaux: ['DURAS N', 'FER N', 'PRUNELARD N', 'SYRAH N']
            cepages_duras_fer_prunelard: ['DURAS N', 'FER N', 'PRUNELARD N']
            cepages_secondaires: ['CABERNET-SAUVIGNON N', 'GAMAY N, MERLOT N']
            cepages_accessoires: ['CABERNET FRANC N']
          regles:
            -
              fonction: 'ProportionSomme'
              category: 'cepages_couleur'
              sens: ">="
              limit: 1
            -
              fonction: 'ProportionSomme'
              category: 'cepages_principaux'
              sens: ">="
              limit: 0.70
            -
              fonction: "Nombre"
              category: "cepages_principaux"
              sens: ">="
              limit: 1
            -
              fonction: 'ProportionSomme'
              category: 'cepages_duras_fer_prunelard'
              sens: ">="
              limit: 0.40
            -
              fonction: 'ProportionSomme'
              category: 'cepages_secondaires'
              sens: "<="
              limit: 0.30
        gaillac_rouge_primeur:
          synthese_libelle: "Gaillac - Primeur Rouge"
          filter_parcellaire_produit_hash: 'appellations/GLC'
          produit_hash: 'certifications/AOP/genres/TRANQ/appellations/GLC/mentions/PM/lieux/DEFAUT/couleurs/rouge/cepages/DEFAUT'
          has_affectation: true
          denomination_aire: "AOC Gaillac"
          parcellaire2reference: 'ParcellaireAffectation'
          categories:
            cepages_principaux: ['GAMAY N']
          regles:
            -
              fonction: 'ProportionSomme'
              category: 'cepages_couleur'
              sens: ">="
              limit: 1
            -
              fonction: 'ProportionSomme'
              category: 'cepages_principaux'
              sens: ">="
              limit: 1
        gaillac_mousseux_ancestrale:
          synthese_libelle: "Gaillac - Mousseux Méthode Ancestrale"
          filter_parcellaire_produit_hash: 'appellations/GLC'
          produit_hash: 'certifications/AOP/genres/MOU/appellations/GLC/mentions/MA/lieux/DEFAUT/couleurs/blanc/cepages/DEFAUT'
          has_affectation: true
          denomination_aire: "AOC Gaillac"
          parcellaire2reference: 'ParcellaireAffectation'
          categories:
            cepages_principaux: ['MAUZAC B', 'MAUZAC ROSE RS']
          regles:
            -
              fonction: 'ProportionSomme'
              category: 'cepages_couleur'
              sens: ">="
              limit: 1
            -
              fonction: 'ProportionSomme'
              category: 'cepages_principaux'
              sens: ">="
              limit: 1
        gaillac_mousseux_ancestrale_doux:
          synthese_libelle: "Gaillac - Mousseux Méthode Ancestrale Doux"
          filter_parcellaire_produit_hash: 'appellations/GLC'
          produit_hash: 'certifications/AOP/genres/MOU/appellations/GLC/mentions/MA/lieux/DEFAUT/couleurs/blanc_doux/cepages/DEFAUT'
          has_affectation: true
          denomination_aire: "AOC Gaillac"
          parcellaire2reference: 'ParcellaireAffectation'
          categories:
            cepages_principaux: ['MAUZAC B', 'MAUZAC ROSE RS']
          regles:
            -
              fonction: 'ProportionSomme'
              category: 'cepages_couleur'
              sens: ">="
              limit: 1
            -
              fonction: 'ProportionSomme'
              category: 'cepages_principaux'
              sens: ">="
              limit: 1
        gaillac_mousseux_tranditionnel:
          synthese_libelle: "Gaillac - Mousseux Méthode Traditionnelle"
          filter_parcellaire_produit_hash: 'appellations/GLC'
          produit_hash: 'certifications/AOP/genres/MOU/appellations/GLC/mentions/DEFAUT/lieux/DEFAUT/couleurs/blanc/cepages/DEFAUT'
          has_affectation: true
          denomination_aire: "AOC Gaillac"
          parcellaire2reference: 'ParcellaireAffectation'
          categories:
            cepages_principaux: ["LEN DE L'EL B", 'MAUZAC B', 'MAUZAC ROSE RS', 'MUSCADELLE B']
            cepages_accessoires: ['ONDENC B', 'SAUVIGNON B']
          regles:
            -
              fonction: 'ProportionSomme'
              category: 'cepages_couleur'
              sens: ">="
              limit: 1
            -
              fonction: 'ProportionSomme'
              category: 'cepages_principaux'
              sens: ">="
              limit: 0.50
            -
              fonction: 'ProportionSomme'
              category: 'cepages_accessoires'
              sens: "<="
              limit: 0.50
        gaillac_blanc_tardive:
          synthese_libelle: "Gaillac - Blanc doux Vendanges tardives"
          filter_parcellaire_produit_hash: 'appellations/GLC'
          produit_hash: 'certifications/AOP/genres/TRANQ/appellations/GLC/mentions/VT/lieux/DEFAUT/couleurs/blanc_doux/cepages/DEFAUT'
          has_affectation: true
          denomination_aire: "AOC Gaillac"
          parcellaire2reference: 'ParcellaireAffectation'
          categories:
            cepages_principaux: ["LEN DE L'EL B", "ONDENC B"]
            cepages_secondaires: ["MAUZAC B, MAUZAC ROSE RS, MUSCADELLE B"]
          regles:
            -
              fonction: 'ProportionSomme'
              category: 'cepages_couleur'
              sens: ">="
              limit: 1
            -
              fonction: 'ProportionSomme'
              category: 'cepages_principaux'
              sens: ">="
              limit: 0.50
            -
              fonction: 'ProportionSomme'
              category: 'cepages_secondaires'
              sens: "<="
              limit: 0.50
