all:
  configuration:
    societe:
      visualisation_teledeclaration: true
      droits:
          "degustateur:porteur_de_memoire": "Dégustateur : Porteur de memoire"
          "degustateur:technicien": "Dégustateur : Technicien"
          "degustateur:usager_du_produit": "Dégustateur : Usager du produit"
